### ISSUE TITLE
block issue: [if on edge, bounce] does not work..

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [pystage/pystage#16]
"a picture is worth a thousand words.."
This gif explains it all
![Recorded](https://user-images.githubusercontent.com/72214351/128605294-a34716db-a4ec-4be3-8ecb-c55c8e4d99d0.gif)

**Comment by Whirlpool-Programmer** [comment]
both are actually from the same .sb3 file, one is on scratch, the other is converted

**Comment by kaiec** [comment]
Thanks. This one is already implemented, but looks like if I messed up somewhere ;-)

https://github.com/pystage/pystage/blob/490e9ac18043b3992089d3e759ab0768907c6b50/src/pystage/core/_motion.py#L134

I will have a look at it.

**Comment by kaiec** [comment]
One thought, though: Scratch uses SVG for the Sprite costumes, which is not supported by Pygame. Pystage does a conversion, but I would not trust it, your circle looks not correct at least. I would convert the SVG manually with Inkscape.

**Comment by kaiec** [comment]
@Whirlpool-Programmer Ok, this was trickier than I thought. In the end it was (probably) a combination of changes in the bounding box when the sprite is rotated and (again) rounding errors when the sprite is positioned on whole pixels. Please let me know if the problem is fixed for you, then I merge into main.
